### ISSUE TITLE
Add a Tweets class that will be able to get all tweets for an individual

### ISSUE THREAD

**Issue by ridwanmsharif** [ridwanmsharif/rudy#1]
In `tweets.py` add a class that initializes a connection with the Twitter API and is able to collect all tweets for a given individual.

The interface I'm imagining looks like the following:

```
class Tweets:
    def __init__(self, auth):
    ....

    def getAll(self, handle):
    ....
```

**Comment by a-sohail** [comment]
idk how to add myself as an assignee but i'll do this

**Comment by ridwanmsharif** [comment]
This is done
